// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "type/class.hpp"
#include "type/inner.hpp"
#include "type/other.hpp"
#include "type/type.hpp"
