// Generated by macro 'mkheader'.
// This file is automatically generated, please do not modify it.
#pragma once
#include "ast/ast.hpp"
#include "ast/container/container.hpp"
#include "ast/evaluable/evaluable.hpp"
#include "ast/evaluable/literal.hpp"
#include "ast/statement/statement.hpp"
#include "ast/type/inner.hpp"
#include "ast/type/other.hpp"
#include "ast/type/type.hpp"
